name: I Had Ten Dollars
url: http://ihadtendollars.com

gems :
  - jekyll-paginate

markdown: kramdown
permalink: interviews/:title.html
exclude: [links, README.md, tasks, wares]
paginate: 10

kramdown:
  auto_ids: false
